# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2021 Suguru Saito <sg.sgch07@gmail.com>
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

ifndef	CONFIG_SPL_BUILD
obj-y	:= pwg5300.o
else
obj-y	:= iomux.o
endif
